(require 'eno)
(require 'bind-key)
(require 'edit-at-point)

(defun eno-word-copy-and-yank ()
  (interactive)
  (eno-word-copy)
  (yank)
  )

(defun eno-word-replace ()
  (interactive)
  (eno-word-copy)
  (edit-at-point-word-paste)
  )

(defun eno-word-cut-and-yank ()
  (interactive)
  (eno-word-cut)
  (edit-at-point-word-paste)
  )

(bind-keys
 ("C-S-M-w g" . eno-word-goto)
 ("C-S-M-w c" . eno-word-copy)
 ("C-S-M-w k" . eno-word-cut)
 ("C-S-M-w s" . eno-word-swap)
 ("C-S-M-w p" . eno-word-paste)
 ("C-S-M-w C-c" . eno-word-copy-and-yank)
 ("C-S-M-w C-r" . eno-word-replace)

 ("C-S-M-s g" . eno-symbol-goto)
 ("C-S-M-s c" . eno-symbol-copy)
 ("C-S-M-s k" . eno-symbol-cut)
 ("C-S-M-s s" . eno-symbol-swap)
 ("C-S-M-s p" . eno-symbol-paste)

 ("C-S-M-t g" . eno-str-goto)
 ("C-S-M-t c" . eno-str-copy)
 ("C-S-M-t k" . eno-str-cut)
 ("C-S-M-t p" . eno-str-paste)

 ("C-S-M-l g" . eno-line-goto)
 ("C-S-M-l c" . eno-line-copy)
 ("C-S-M-l k" . eno-line-cut)
 ("C-S-M-l p" . eno-line-paste)

 ("C-S-M-p g" . eno-paren-goto)
 ("C-S-M-p c" . eno-paren-copy)
 ("C-S-M-p k" . eno-paren-cut)
 ("C-S-M-p p" . eno-paren-paste))

(eno-set-all-letter-str " sdfjkla;weioqpruvncmghxz,./")
(eno-set-same-finger-list '("qaz" "wsx" "edc" "rfvg" "ujmh" "ik" "ol." "p;/"))
(setq eno-stay-key-list '("<prior>" "<next>" "<wheel-up>" "<wheel-down>"))
